# Generated by Django 5.0.6 on 2024-05-26 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 5, 26, 17, 59, 48, 517153, tzinfo=datetime.timezone.utc))),
                ('due_at', models.DateTimeField()),
            ],
        ),
    ]
